{% set name = "pyflowchart" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflowchart-{{ version }}.tar.gz
  sha256: 4268699c4d11d1ab4e5276a12441f7eea6468ee3d87fadb54a4d2449cc3526c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astunparse
    - chardet

test:
  imports:
    - pyflowchart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cdfmlr/pyflowchart
  summary: Python codes to Flowcharts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
