{% set name = "pyflowchart" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflowchart-{{ version }}.tar.gz
  sha256: 91c0f4c2a85cc2d2df777ed41a1ff0f40dfdf955d6196e5c63508dd71097eacb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astunparse
    - chardet

test:
  imports:
    - pyflowchart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cdfmlr/pyflowchart
  summary: Python codes to Flowcharts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
